name: "Lint"

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.2500.0
        continue-on-error: true
        with:
          directory: .
          quiet: true # optional: display only failed checks

#  super-linter:
#    name: SuperLinter
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: read
#      packages: read
#      statuses: write
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#
#      - name: Run SuperLinter action
#        uses: super-linter/super-linter/slim@v5
#        env:
#          VALIDATE_ALL_CODEBASE: false
#          DEFAULT_BRANCH: main
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
